export { default as Home } from "./Home"
export { default as GeoPosition } from "./GeoPosition"
export { default as Constraints } from "./Constraints"
export { default as PowerConsumption } from "./PowerConsumption"
export { default as Results } from "./Results"
export { default as Succes } from "./Succes"